### ISSUE TITLE
Answer in 4.2 exercise does not work.

### ISSUE THREAD

**Issue by letto4135** [rustwasm/book#261]
**Describe the bug**
Everything seems to be working as expected until I get to the exercise. Updating the code and running wasm-pack build does nothing to the front end.

**To Reproduce**
Follow instructions up to the exercise in 4.2

**Expected behavior**
The exercise should work.

**Screenshots**
<img width="518" alt="Screen Shot 2021-09-28 at 8 39 28 PM" src="https://user-images.githubusercontent.com/35670693/135184005-fdb46e71-a6ec-420e-920c-3381b36481dd.png">
<img width="518" alt="Screen Shot 2021-09-28 at 8 39 46 PM" src="https://user-images.githubusercontent.com/35670693/135184043-f8f29da1-52ee-42f7-9b52-793775ae89a5.png">
<img width="443" alt="Screen Shot 2021-09-28 at 8 40 21 PM" src="https://user-images.githubusercontent.com/35670693/135184050-8f64b082-b7ac-4406-8795-15cb065128ce.png">

**Comment by joshuaalm** [comment]
I get the same behavior
![image](https://user-images.githubusercontent.com/6978629/142635018-0ce41ad8-312b-430a-8bd8-dc42e7c51871.png)
![image](https://user-images.githubusercontent.com/6978629/142635050-bebeb7ba-526e-416c-8ff4-6d8ea1cf043b.png)
![image](https://user-images.githubusercontent.com/6978629/142635116-d0a308a6-351f-49f6-a4dc-31e096e4e2ec.png)

**Comment by abiriadev** [comment]
same here.
this is not the browser's cache problem, I've tested this in other browsers but the final .wasm file (when manually build with webpack, in dist directory) doesn't change.
(while other .wasm file in pkg directory is changed.)

**Comment by armenic** [comment]
The reason is because `npm install` already captured the old version of `wasm-game-of-life`. To fix this:
1. Up-version in the `Cargo.toml`, e.g. `"0.1.1"`
2. Within the `wasm-game-of-life directory` run `wasm-pack build`
3. Within the `www` directory run `npm install wasm-game-of-life`
4. You might also need to stop and restart the local server

![image](https://user-images.githubusercontent.com/71098506/201232465-0d038e1d-4f8f-4591-b56c-4e14f4aec727.png)

**Comment by erikbrntsn** [comment]
I have a similar problem. Only the result of the first compilation is ever used. Any changes after compiling the first time have no effect.
I have tried changing the version in the cargo.toml + restarted the server + uninstall wasm-game-of-life and readded in to the dependencies section + removed the www app and recreated it. None of these steps help :(

The only way I have found to get around the problem is to remove the entire wasm-game-of-life folder and recreating it + applying all the changes to the code before running `wasm-pack build`

Note this is the case for the steps in the subsection "Implementing Life" as well

**Comment by letto4135** [comment]
Sorry, I'm just going to close this. I can't remember at this point if I ever got it to work, and I don't have anything set up to know whether armenics answer works.

**Comment by ptdecker** [comment]
@armenic 's answer worked for me. I know this issue has been closed but it doesn't appear the instructions for the tutorial have been corrected (in fact, it doesn't seem like there is much activity towards maintaining this book unfortunately--lots of accumulated issues and pull requests that are unattended).
