### ISSUE TITLE
hello world, rebuilding unclear

### ISSUE THREAD

**Issue by aep** [rustwasm/book#84]
**Where in the docs did you come across this?**

https://rustwasm.github.io/book/game-of-life/hello-world.html

**Describe what about it does not make sense**

Exercises says  "rebuild the .wasm binary,", but no text before that explains how you actually do that. The only command that was mentioned before is wasm-pack init, 

**Why does it not make sense?**

according to https://github.com/rustwasm/wasm-pack/issues/185 the correct command is
 
    wasm-pack init --mode no-install 

but that is non obvious

**How could we improve it?**

mention wasm-pack init --mode no-install

**Comment by rahul-thakoor** [comment]
Hey there. I was just completing the hello-world tutorial. A note in the book stating that one can use `wasm-pack init --mode no-install`(or `wasm-pack build --mode no-install` eventually since `init` is [DEPRECATED](https://rustwasm.github.io/wasm-pack/commands/init.html)) to skip installing `wasm-bindgen` would be helpful...
